; File auto-generated from https://api.github.com/emojis via json-to-ahk.jq

:?*:\`:?::
  Run "https://www.spinellis.gr/sw/unicode-hotstrings/emojis.html"

:O:\`:+1::👍
:O:\`:-1::👎
:O:\`:100::💯
:O:\`:1234::🔢
:O:\`:1st_place_medal::🥇
:O:\`:2nd_place_medal::🥈
:O:\`:3rd_place_medal::🥉
:O:\`:8ball::🎱
:O:\`:a::🅰
:O:\`:ab::🆎
:O:\`:abacus::🧮
:O:\`:abc::🔤
:O:\`:abcd::🔡
:O:\`:accept::🉑
:O:\`:accordion::🪗
:O:\`:adhesive_bandage::🩹
:O:\`:adult::🧑
:O:\`:aerial_tramway::🚡
:O:\`:afghanistan::🇦🇫
:O:\`:airplane::✈
:O:\`:aland_islands::🇦🇽
:O:\`:alarm_clock::⏰
:O:\`:albania::🇦🇱
:O:\`:alembic::⚗
:O:\`:algeria::🇩🇿
:O:\`:alien::👽
:O:\`:ambulance::🚑
:O:\`:american_samoa::🇦🇸
:O:\`:amphora::🏺
:O:\`:anatomical_heart::🫀
:O:\`:anchor::⚓
:O:\`:andorra::🇦🇩
:O:\`:angel::👼
:O:\`:anger::💢
:O:\`:angola::🇦🇴
:O:\`:angry::😠
:O:\`:anguilla::🇦🇮
:O:\`:anguished::😧
:O:\`:ant::🐜
:O:\`:antarctica::🇦🇶
:O:\`:antigua_barbuda::🇦🇬
:O:\`:apple::🍎
:O:\`:aquarius::♒
:O:\`:argentina::🇦🇷
:O:\`:aries::♈
:O:\`:armenia::🇦🇲
:O:\`:arrow_backward::◀
:O:\`:arrow_double_down::⏬
:O:\`:arrow_double_up::⏫
:O:\`:arrow_down::⬇
:O:\`:arrow_down_small::🔽
:O:\`:arrow_forward::▶
:O:\`:arrow_heading_down::⤵
:O:\`:arrow_heading_up::⤴
:O:\`:arrow_left::⬅
:O:\`:arrow_lower_left::↙
:O:\`:arrow_lower_right::↘
:O:\`:arrow_right::➡
:O:\`:arrow_right_hook::↪
:O:\`:arrow_up::⬆
:O:\`:arrow_up_down::↕
:O:\`:arrow_up_small::🔼
:O:\`:arrow_upper_left::↖
:O:\`:arrow_upper_right::↗
:O:\`:arrows_clockwise::🔃
:O:\`:arrows_counterclockwise::🔄
:O:\`:art::🎨
:O:\`:articulated_lorry::🚛
:O:\`:artificial_satellite::🛰
:O:\`:artist::🧑🎨
:O:\`:aruba::🇦🇼
:O:\`:ascension_island::🇦🇨
:O:\`:asterisk::*⃣
:O:\`:astonished::😲
:O:\`:astronaut::🧑🚀
:O:\`:athletic_shoe::👟
:O:\`:atm::🏧
:O:\`:atom_symbol::⚛
:O:\`:australia::🇦🇺
:O:\`:austria::🇦🇹
:O:\`:auto_rickshaw::🛺
:O:\`:avocado::🥑
:O:\`:axe::🪓
:O:\`:azerbaijan::🇦🇿
:O:\`:b::🅱
:O:\`:baby::👶
:O:\`:baby_bottle::🍼
:O:\`:baby_chick::🐤
:O:\`:baby_symbol::🚼
:O:\`:back::🔙
:O:\`:bacon::🥓
:O:\`:badger::🦡
:O:\`:badminton::🏸
:O:\`:bagel::🥯
:O:\`:baggage_claim::🛄
:O:\`:baguette_bread::🥖
:O:\`:bahamas::🇧🇸
:O:\`:bahrain::🇧🇭
:O:\`:balance_scale::⚖
:O:\`:bald_man::👨🦲
:O:\`:bald_woman::👩🦲
:O:\`:ballet_shoes::🩰
:O:\`:balloon::🎈
:O:\`:ballot_box::🗳
:O:\`:ballot_box_with_check::☑
:O:\`:bamboo::🎍
:O:\`:banana::🍌
:O:\`:bangbang::‼
:O:\`:bangladesh::🇧🇩
:O:\`:banjo::🪕
:O:\`:bank::🏦
:O:\`:bar_chart::📊
:O:\`:barbados::🇧🇧
:O:\`:barber::💈
:O:\`:baseball::⚾
:O:\`:basket::🧺
:O:\`:basketball::🏀
:O:\`:basketball_man::⛹♂
:O:\`:basketball_woman::⛹♀
:O:\`:bat::🦇
:O:\`:bath::🛀
:O:\`:bathtub::🛁
:O:\`:battery::🔋
:O:\`:beach_umbrella::🏖
:O:\`:bear::🐻
:O:\`:bearded_person::🧔
:O:\`:beaver::🦫
:O:\`:bed::🛏
:O:\`:bee::🐝
:O:\`:beer::🍺
:O:\`:beers::🍻
:O:\`:beetle::🪲
:O:\`:beginner::🔰
:O:\`:belarus::🇧🇾
:O:\`:belgium::🇧🇪
:O:\`:belize::🇧🇿
:O:\`:bell::🔔
:O:\`:bell_pepper::🫑
:O:\`:bellhop_bell::🛎
:O:\`:benin::🇧🇯
:O:\`:bento::🍱
:O:\`:bermuda::🇧🇲
:O:\`:beverage_box::🧃
:O:\`:bhutan::🇧🇹
:O:\`:bicyclist::🚴
:O:\`:bike::🚲
:O:\`:biking_man::🚴♂
:O:\`:biking_woman::🚴♀
:O:\`:bikini::👙
:O:\`:billed_cap::🧢
:O:\`:biohazard::☣
:O:\`:bird::🐦
:O:\`:birthday::🎂
:O:\`:bison::🦬
:O:\`:black_cat::🐈⬛
:O:\`:black_circle::⚫
:O:\`:black_flag::🏴
:O:\`:black_heart::🖤
:O:\`:black_joker::🃏
:O:\`:black_large_square::⬛
:O:\`:black_medium_small_square::◾
:O:\`:black_medium_square::◼
:O:\`:black_nib::✒
:O:\`:black_small_square::▪
:O:\`:black_square_button::🔲
:O:\`:blond_haired_man::👱♂
:O:\`:blond_haired_person::👱
:O:\`:blond_haired_woman::👱♀
:O:\`:blonde_woman::👱♀
:O:\`:blossom::🌼
:O:\`:blowfish::🐡
:O:\`:blue_book::📘
:O:\`:blue_car::🚙
:O:\`:blue_heart::💙
:O:\`:blue_square::🟦
:O:\`:blueberries::🫐
:O:\`:blush::😊
:O:\`:boar::🐗
:O:\`:boat::⛵
:O:\`:bolivia::🇧🇴
:O:\`:bomb::💣
:O:\`:bone::🦴
:O:\`:book::📖
:O:\`:bookmark::🔖
:O:\`:bookmark_tabs::📑
:O:\`:books::📚
:O:\`:boom::💥
:O:\`:boomerang::🪃
:O:\`:boot::👢
:O:\`:bosnia_herzegovina::🇧🇦
:O:\`:botswana::🇧🇼
:O:\`:bouncing_ball_man::⛹♂
:O:\`:bouncing_ball_person::⛹
:O:\`:bouncing_ball_woman::⛹♀
:O:\`:bouquet::💐
:O:\`:bouvet_island::🇧🇻
:O:\`:bow::🙇
:O:\`:bow_and_arrow::🏹
:O:\`:bowing_man::🙇♂
:O:\`:bowing_woman::🙇♀
:O:\`:bowl_with_spoon::🥣
:O:\`:bowling::🎳
:O:\`:boxing_glove::🥊
:O:\`:boy::👦
:O:\`:brain::🧠
:O:\`:brazil::🇧🇷
:O:\`:bread::🍞
:O:\`:breast_feeding::🤱
:O:\`:bricks::🧱
:O:\`:bride_with_veil::👰♀
:O:\`:bridge_at_night::🌉
:O:\`:briefcase::💼
:O:\`:british_indian_ocean_territory::🇮🇴
:O:\`:british_virgin_islands::🇻🇬
:O:\`:broccoli::🥦
:O:\`:broken_heart::💔
:O:\`:broom::🧹
:O:\`:brown_circle::🟤
:O:\`:brown_heart::🤎
:O:\`:brown_square::🟫
:O:\`:brunei::🇧🇳
:O:\`:bubble_tea::🧋
:O:\`:bucket::🪣
:O:\`:bug::🐛
:O:\`:building_construction::🏗
:O:\`:bulb::💡
:O:\`:bulgaria::🇧🇬
:O:\`:bullettrain_front::🚅
:O:\`:bullettrain_side::🚄
:O:\`:burkina_faso::🇧🇫
:O:\`:burrito::🌯
:O:\`:burundi::🇧🇮
:O:\`:bus::🚌
:O:\`:business_suit_levitating::🕴
:O:\`:busstop::🚏
:O:\`:bust_in_silhouette::👤
:O:\`:busts_in_silhouette::👥
:O:\`:butter::🧈
:O:\`:butterfly::🦋
:O:\`:cactus::🌵
:O:\`:cake::🍰
:O:\`:calendar::📆
:O:\`:call_me_hand::🤙
:O:\`:calling::📲
:O:\`:cambodia::🇰🇭
:O:\`:camel::🐫
:O:\`:camera::📷
:O:\`:camera_flash::📸
:O:\`:cameroon::🇨🇲
:O:\`:camping::🏕
:O:\`:canada::🇨🇦
:O:\`:canary_islands::🇮🇨
:O:\`:cancer::♋
:O:\`:candle::🕯
:O:\`:candy::🍬
:O:\`:canned_food::🥫
:O:\`:canoe::🛶
:O:\`:cape_verde::🇨🇻
:O:\`:capital_abcd::🔠
:O:\`:capricorn::♑
:O:\`:car::🚗
:O:\`:card_file_box::🗃
:O:\`:card_index::📇
:O:\`:card_index_dividers::🗂
:O:\`:caribbean_netherlands::🇧🇶
:O:\`:carousel_horse::🎠
:O:\`:carpentry_saw::🪚
:O:\`:carrot::🥕
:O:\`:cartwheeling::🤸
:O:\`:cat::🐱
:O:\`:cat2::🐈
:O:\`:cayman_islands::🇰🇾
:O:\`:cd::💿
:O:\`:central_african_republic::🇨🇫
:O:\`:ceuta_melilla::🇪🇦
:O:\`:chad::🇹🇩
:O:\`:chains::⛓
:O:\`:chair::🪑
:O:\`:champagne::🍾
:O:\`:chart::💹
:O:\`:chart_with_downwards_trend::📉
:O:\`:chart_with_upwards_trend::📈
:O:\`:checkered_flag::🏁
:O:\`:cheese::🧀
:O:\`:cherries::🍒
:O:\`:cherry_blossom::🌸
:O:\`:chess_pawn::♟
:O:\`:chestnut::🌰
:O:\`:chicken::🐔
:O:\`:child::🧒
:O:\`:children_crossing::🚸
:O:\`:chile::🇨🇱
:O:\`:chipmunk::🐿
:O:\`:chocolate_bar::🍫
:O:\`:chopsticks::🥢
:O:\`:christmas_island::🇨🇽
:O:\`:christmas_tree::🎄
:O:\`:church::⛪
:O:\`:cinema::🎦
:O:\`:circus_tent::🎪
:O:\`:city_sunrise::🌇
:O:\`:city_sunset::🌆
:O:\`:cityscape::🏙
:O:\`:cl::🆑
:O:\`:clamp::🗜
:O:\`:clap::👏
:O:\`:clapper::🎬
:O:\`:classical_building::🏛
:O:\`:climbing::🧗
:O:\`:climbing_man::🧗♂
:O:\`:climbing_woman::🧗♀
:O:\`:clinking_glasses::🥂
:O:\`:clipboard::📋
:O:\`:clipperton_island::🇨🇵
:O:\`:clock1::🕐
:O:\`:clock10::🕙
:O:\`:clock1030::🕥
:O:\`:clock11::🕚
:O:\`:clock1130::🕦
:O:\`:clock12::🕛
:O:\`:clock1230::🕧
:O:\`:clock130::🕜
:O:\`:clock2::🕑
:O:\`:clock230::🕝
:O:\`:clock3::🕒
:O:\`:clock330::🕞
:O:\`:clock4::🕓
:O:\`:clock430::🕟
:O:\`:clock5::🕔
:O:\`:clock530::🕠
:O:\`:clock6::🕕
:O:\`:clock630::🕡
:O:\`:clock7::🕖
:O:\`:clock730::🕢
:O:\`:clock8::🕗
:O:\`:clock830::🕣
:O:\`:clock9::🕘
:O:\`:clock930::🕤
:O:\`:closed_book::📕
:O:\`:closed_lock_with_key::🔐
:O:\`:closed_umbrella::🌂
:O:\`:cloud::☁
:O:\`:cloud_with_lightning::🌩
:O:\`:cloud_with_lightning_and_rain::⛈
:O:\`:cloud_with_rain::🌧
:O:\`:cloud_with_snow::🌨
:O:\`:clown_face::🤡
:O:\`:clubs::♣
:O:\`:cn::🇨🇳
:O:\`:coat::🧥
:O:\`:cockroach::🪳
:O:\`:cocktail::🍸
:O:\`:coconut::🥥
:O:\`:cocos_islands::🇨🇨
:O:\`:coffee::☕
:O:\`:coffin::⚰
:O:\`:coin::🪙
:O:\`:cold_face::🥶
:O:\`:cold_sweat::😰
:O:\`:collision::💥
:O:\`:colombia::🇨🇴
:O:\`:comet::☄
:O:\`:comoros::🇰🇲
:O:\`:compass::🧭
:O:\`:computer::💻
:O:\`:computer_mouse::🖱
:O:\`:confetti_ball::🎊
:O:\`:confounded::😖
:O:\`:confused::😕
:O:\`:congo_brazzaville::🇨🇬
:O:\`:congo_kinshasa::🇨🇩
:O:\`:congratulations::㊗
:O:\`:construction::🚧
:O:\`:construction_worker::👷
:O:\`:construction_worker_man::👷♂
:O:\`:construction_worker_woman::👷♀
:O:\`:control_knobs::🎛
:O:\`:convenience_store::🏪
:O:\`:cook::🧑🍳
:O:\`:cook_islands::🇨🇰
:O:\`:cookie::🍪
:O:\`:cool::🆒
:O:\`:cop::👮
:O:\`:copyright::©
:O:\`:corn::🌽
:O:\`:costa_rica::🇨🇷
:O:\`:cote_divoire::🇨🇮
:O:\`:couch_and_lamp::🛋
:O:\`:couple::👫
:O:\`:couple_with_heart::💑
:O:\`:couple_with_heart_man_man::👨❤👨
:O:\`:couple_with_heart_woman_man::👩❤👨
:O:\`:couple_with_heart_woman_woman::👩❤👩
:O:\`:couplekiss::💏
:O:\`:couplekiss_man_man::👨❤💋👨
:O:\`:couplekiss_man_woman::👩❤💋👨
:O:\`:couplekiss_woman_woman::👩❤💋👩
:O:\`:cow::🐮
:O:\`:cow2::🐄
:O:\`:cowboy_hat_face::🤠
:O:\`:crab::🦀
:O:\`:crayon::🖍
:O:\`:credit_card::💳
:O:\`:crescent_moon::🌙
:O:\`:cricket::🦗
:O:\`:cricket_game::🏏
:O:\`:croatia::🇭🇷
:O:\`:crocodile::🐊
:O:\`:croissant::🥐
:O:\`:crossed_fingers::🤞
:O:\`:crossed_flags::🎌
:O:\`:crossed_swords::⚔
:O:\`:crown::👑
:O:\`:cry::😢
:O:\`:crying_cat_face::😿
:O:\`:crystal_ball::🔮
:O:\`:cuba::🇨🇺
:O:\`:cucumber::🥒
:O:\`:cup_with_straw::🥤
:O:\`:cupcake::🧁
:O:\`:cupid::💘
:O:\`:curacao::🇨🇼
:O:\`:curling_stone::🥌
:O:\`:curly_haired_man::👨🦱
:O:\`:curly_haired_woman::👩🦱
:O:\`:curly_loop::➰
:O:\`:currency_exchange::💱
:O:\`:curry::🍛
:O:\`:cursing_face::🤬
:O:\`:custard::🍮
:O:\`:customs::🛃
:O:\`:cut_of_meat::🥩
:O:\`:cyclone::🌀
:O:\`:cyprus::🇨🇾
:O:\`:czech_republic::🇨🇿
:O:\`:dagger::🗡
:O:\`:dancer::💃
:O:\`:dancers::👯
:O:\`:dancing_men::👯♂
:O:\`:dancing_women::👯♀
:O:\`:dango::🍡
:O:\`:dark_sunglasses::🕶
:O:\`:dart::🎯
:O:\`:dash::💨
:O:\`:date::📅
:O:\`:de::🇩🇪
:O:\`:deaf_man::🧏♂
:O:\`:deaf_person::🧏
:O:\`:deaf_woman::🧏♀
:O:\`:deciduous_tree::🌳
:O:\`:deer::🦌
:O:\`:denmark::🇩🇰
:O:\`:department_store::🏬
:O:\`:derelict_house::🏚
:O:\`:desert::🏜
:O:\`:desert_island::🏝
:O:\`:desktop_computer::🖥
:O:\`:detective::🕵
:O:\`:diamond_shape_with_a_dot_inside::💠
:O:\`:diamonds::♦
:O:\`:diego_garcia::🇩🇬
:O:\`:disappointed::😞
:O:\`:disappointed_relieved::😥
:O:\`:disguised_face::🥸
:O:\`:diving_mask::🤿
:O:\`:diya_lamp::🪔
:O:\`:dizzy::💫
:O:\`:dizzy_face::😵
:O:\`:djibouti::🇩🇯
:O:\`:dna::🧬
:O:\`:do_not_litter::🚯
:O:\`:dodo::🦤
:O:\`:dog::🐶
:O:\`:dog2::🐕
:O:\`:dollar::💵
:O:\`:dolls::🎎
:O:\`:dolphin::🐬
:O:\`:dominica::🇩🇲
:O:\`:dominican_republic::🇩🇴
:O:\`:door::🚪
:O:\`:doughnut::🍩
:O:\`:dove::🕊
:O:\`:dragon::🐉
:O:\`:dragon_face::🐲
:O:\`:dress::👗
:O:\`:dromedary_camel::🐪
:O:\`:drooling_face::🤤
:O:\`:drop_of_blood::🩸
:O:\`:droplet::💧
:O:\`:drum::🥁
:O:\`:duck::🦆
:O:\`:dumpling::🥟
:O:\`:dvd::📀
:O:\`:e-mail::📧
:O:\`:eagle::🦅
:O:\`:ear::👂
:O:\`:ear_of_rice::🌾
:O:\`:ear_with_hearing_aid::🦻
:O:\`:earth_africa::🌍
:O:\`:earth_americas::🌎
:O:\`:earth_asia::🌏
:O:\`:ecuador::🇪🇨
:O:\`:egg::🥚
:O:\`:eggplant::🍆
:O:\`:egypt::🇪🇬
:O:\`:eight::8⃣
:O:\`:eight_pointed_black_star::✴
:O:\`:eight_spoked_asterisk::✳
:O:\`:eject_button::⏏
:O:\`:el_salvador::🇸🇻
:O:\`:electric_plug::🔌
:O:\`:elephant::🐘
:O:\`:elevator::🛗
:O:\`:elf::🧝
:O:\`:elf_man::🧝♂
:O:\`:elf_woman::🧝♀
:O:\`:email::📧
:O:\`:end::🔚
:O:\`:england::🏴󠁧󠁢󠁥󠁮󠁧󠁿
:O:\`:envelope::✉
:O:\`:envelope_with_arrow::📩
:O:\`:equatorial_guinea::🇬🇶
:O:\`:eritrea::🇪🇷
:O:\`:es::🇪🇸
:O:\`:estonia::🇪🇪
:O:\`:ethiopia::🇪🇹
:O:\`:eu::🇪🇺
:O:\`:euro::💶
:O:\`:european_castle::🏰
:O:\`:european_post_office::🏤
:O:\`:european_union::🇪🇺
:O:\`:evergreen_tree::🌲
:O:\`:exclamation::❗
:O:\`:exploding_head::🤯
:O:\`:expressionless::😑
:O:\`:eye::👁
:O:\`:eye_speech_bubble::👁🗨
:O:\`:eyeglasses::👓
:O:\`:eyes::👀
:O:\`:face_exhaling::😮💨
:O:\`:face_in_clouds::😶🌫
:O:\`:face_with_head_bandage::🤕
:O:\`:face_with_spiral_eyes::😵💫
:O:\`:face_with_thermometer::🤒
:O:\`:facepalm::🤦
:O:\`:facepunch::👊
:O:\`:factory::🏭
:O:\`:factory_worker::🧑🏭
:O:\`:fairy::🧚
:O:\`:fairy_man::🧚♂
:O:\`:fairy_woman::🧚♀
:O:\`:falafel::🧆
:O:\`:falkland_islands::🇫🇰
:O:\`:fallen_leaf::🍂
:O:\`:family::👪
:O:\`:family_man_boy::👨👦
:O:\`:family_man_boy_boy::👨👦👦
:O:\`:family_man_girl::👨👧
:O:\`:family_man_girl_boy::👨👧👦
:O:\`:family_man_girl_girl::👨👧👧
:O:\`:family_man_man_boy::👨👨👦
:O:\`:family_man_man_boy_boy::👨👨👦👦
:O:\`:family_man_man_girl::👨👨👧
:O:\`:family_man_man_girl_boy::👨👨👧👦
:O:\`:family_man_man_girl_girl::👨👨👧👧
:O:\`:family_man_woman_boy::👨👩👦
:O:\`:family_man_woman_boy_boy::👨👩👦👦
:O:\`:family_man_woman_girl::👨👩👧
:O:\`:family_man_woman_girl_boy::👨👩👧👦
:O:\`:family_man_woman_girl_girl::👨👩👧👧
:O:\`:family_woman_boy::👩👦
:O:\`:family_woman_boy_boy::👩👦👦
:O:\`:family_woman_girl::👩👧
:O:\`:family_woman_girl_boy::👩👧👦
:O:\`:family_woman_girl_girl::👩👧👧
:O:\`:family_woman_woman_boy::👩👩👦
:O:\`:family_woman_woman_boy_boy::👩👩👦👦
:O:\`:family_woman_woman_girl::👩👩👧
:O:\`:family_woman_woman_girl_boy::👩👩👧👦
:O:\`:family_woman_woman_girl_girl::👩👩👧👧
:O:\`:farmer::🧑🌾
:O:\`:faroe_islands::🇫🇴
:O:\`:fast_forward::⏩
:O:\`:fax::📠
:O:\`:fearful::😨
:O:\`:feather::🪶
:O:\`:feet::🐾
:O:\`:female_detective::🕵♀
:O:\`:female_sign::♀
:O:\`:ferris_wheel::🎡
:O:\`:ferry::⛴
:O:\`:field_hockey::🏑
:O:\`:fiji::🇫🇯
:O:\`:file_cabinet::🗄
:O:\`:file_folder::📁
:O:\`:film_projector::📽
:O:\`:film_strip::🎞
:O:\`:finland::🇫🇮
:O:\`:fire::🔥
:O:\`:fire_engine::🚒
:O:\`:fire_extinguisher::🧯
:O:\`:firecracker::🧨
:O:\`:firefighter::🧑🚒
:O:\`:fireworks::🎆
:O:\`:first_quarter_moon::🌓
:O:\`:first_quarter_moon_with_face::🌛
:O:\`:fish::🐟
:O:\`:fish_cake::🍥
:O:\`:fishing_pole_and_fish::🎣
:O:\`:fist::✊
:O:\`:fist_left::🤛
:O:\`:fist_oncoming::👊
:O:\`:fist_raised::✊
:O:\`:fist_right::🤜
:O:\`:five::5⃣
:O:\`:flags::🎏
:O:\`:flamingo::🦩
:O:\`:flashlight::🔦
:O:\`:flat_shoe::🥿
:O:\`:flatbread::🫓
:O:\`:fleur_de_lis::⚜
:O:\`:flight_arrival::🛬
:O:\`:flight_departure::🛫
:O:\`:flipper::🐬
:O:\`:floppy_disk::💾
:O:\`:flower_playing_cards::🎴
:O:\`:flushed::😳
:O:\`:fly::🪰
:O:\`:flying_disc::🥏
:O:\`:flying_saucer::🛸
:O:\`:fog::🌫
:O:\`:foggy::🌁
:O:\`:fondue::🫕
:O:\`:foot::🦶
:O:\`:football::🏈
:O:\`:footprints::👣
:O:\`:fork_and_knife::🍴
:O:\`:fortune_cookie::🥠
:O:\`:fountain::⛲
:O:\`:fountain_pen::🖋
:O:\`:four::4⃣
:O:\`:four_leaf_clover::🍀
:O:\`:fox_face::🦊
:O:\`:fr::🇫🇷
:O:\`:framed_picture::🖼
:O:\`:free::🆓
:O:\`:french_guiana::🇬🇫
:O:\`:french_polynesia::🇵🇫
:O:\`:french_southern_territories::🇹🇫
:O:\`:fried_egg::🍳
:O:\`:fried_shrimp::🍤
:O:\`:fries::🍟
:O:\`:frog::🐸
:O:\`:frowning::😦
:O:\`:frowning_face::☹
:O:\`:frowning_man::🙍♂
:O:\`:frowning_person::🙍
:O:\`:frowning_woman::🙍♀
:O:\`:fu::🖕
:O:\`:fuelpump::⛽
:O:\`:full_moon::🌕
:O:\`:full_moon_with_face::🌝
:O:\`:funeral_urn::⚱
:O:\`:gabon::🇬🇦
:O:\`:gambia::🇬🇲
:O:\`:game_die::🎲
:O:\`:garlic::🧄
:O:\`:gb::🇬🇧
:O:\`:gear::⚙
:O:\`:gem::💎
:O:\`:gemini::♊
:O:\`:genie::🧞
:O:\`:genie_man::🧞♂
:O:\`:genie_woman::🧞♀
:O:\`:georgia::🇬🇪
:O:\`:ghana::🇬🇭
:O:\`:ghost::👻
:O:\`:gibraltar::🇬🇮
:O:\`:gift::🎁
:O:\`:gift_heart::💝
:O:\`:giraffe::🦒
:O:\`:girl::👧
:O:\`:globe_with_meridians::🌐
:O:\`:gloves::🧤
:O:\`:goal_net::🥅
:O:\`:goat::🐐
:O:\`:goggles::🥽
:O:\`:golf::⛳
:O:\`:golfing::🏌
:O:\`:golfing_man::🏌♂
:O:\`:golfing_woman::🏌♀
:O:\`:gorilla::🦍
:O:\`:grapes::🍇
:O:\`:greece::🇬🇷
:O:\`:green_apple::🍏
:O:\`:green_book::📗
:O:\`:green_circle::🟢
:O:\`:green_heart::💚
:O:\`:green_salad::🥗
:O:\`:green_square::🟩
:O:\`:greenland::🇬🇱
:O:\`:grenada::🇬🇩
:O:\`:grey_exclamation::❕
:O:\`:grey_question::❔
:O:\`:grimacing::😬
:O:\`:grin::😁
:O:\`:grinning::😀
:O:\`:guadeloupe::🇬🇵
:O:\`:guam::🇬🇺
:O:\`:guard::💂
:O:\`:guardsman::💂♂
:O:\`:guardswoman::💂♀
:O:\`:guatemala::🇬🇹
:O:\`:guernsey::🇬🇬
:O:\`:guide_dog::🦮
:O:\`:guinea::🇬🇳
:O:\`:guinea_bissau::🇬🇼
:O:\`:guitar::🎸
:O:\`:gun::🔫
:O:\`:guyana::🇬🇾
:O:\`:haircut::💇
:O:\`:haircut_man::💇♂
:O:\`:haircut_woman::💇♀
:O:\`:haiti::🇭🇹
:O:\`:hamburger::🍔
:O:\`:hammer::🔨
:O:\`:hammer_and_pick::⚒
:O:\`:hammer_and_wrench::🛠
:O:\`:hamster::🐹
:O:\`:hand::✋
:O:\`:hand_over_mouth::🤭
:O:\`:handbag::👜
:O:\`:handball_person::🤾
:O:\`:handshake::🤝
:O:\`:hankey::💩
:O:\`:hash::#⃣
:O:\`:hatched_chick::🐥
:O:\`:hatching_chick::🐣
:O:\`:headphones::🎧
:O:\`:headstone::🪦
:O:\`:health_worker::🧑⚕
:O:\`:hear_no_evil::🙉
:O:\`:heard_mcdonald_islands::🇭🇲
:O:\`:heart::❤
:O:\`:heart_decoration::💟
:O:\`:heart_eyes::😍
:O:\`:heart_eyes_cat::😻
:O:\`:heart_on_fire::❤🔥
:O:\`:heartbeat::💓
:O:\`:heartpulse::💗
:O:\`:hearts::♥
:O:\`:heavy_check_mark::✔
:O:\`:heavy_division_sign::➗
:O:\`:heavy_dollar_sign::💲
:O:\`:heavy_exclamation_mark::❗
:O:\`:heavy_heart_exclamation::❣
:O:\`:heavy_minus_sign::➖
:O:\`:heavy_multiplication_x::✖
:O:\`:heavy_plus_sign::➕
:O:\`:hedgehog::🦔
:O:\`:helicopter::🚁
:O:\`:herb::🌿
:O:\`:hibiscus::🌺
:O:\`:high_brightness::🔆
:O:\`:high_heel::👠
:O:\`:hiking_boot::🥾
:O:\`:hindu_temple::🛕
:O:\`:hippopotamus::🦛
:O:\`:hocho::🔪
:O:\`:hole::🕳
:O:\`:honduras::🇭🇳
:O:\`:honey_pot::🍯
:O:\`:honeybee::🐝
:O:\`:hong_kong::🇭🇰
:O:\`:hook::🪝
:O:\`:horse::🐴
:O:\`:horse_racing::🏇
:O:\`:hospital::🏥
:O:\`:hot_face::🥵
:O:\`:hot_pepper::🌶
:O:\`:hotdog::🌭
:O:\`:hotel::🏨
:O:\`:hotsprings::♨
:O:\`:hourglass::⌛
:O:\`:hourglass_flowing_sand::⏳
:O:\`:house::🏠
:O:\`:house_with_garden::🏡
:O:\`:houses::🏘
:O:\`:hugs::🤗
:O:\`:hungary::🇭🇺
:O:\`:hushed::😯
:O:\`:hut::🛖
:O:\`:ice_cream::🍨
:O:\`:ice_cube::🧊
:O:\`:ice_hockey::🏒
:O:\`:ice_skate::⛸
:O:\`:icecream::🍦
:O:\`:iceland::🇮🇸
:O:\`:id::🆔
:O:\`:ideograph_advantage::🉐
:O:\`:imp::👿
:O:\`:inbox_tray::📥
:O:\`:incoming_envelope::📨
:O:\`:india::🇮🇳
:O:\`:indonesia::🇮🇩
:O:\`:infinity::♾
:O:\`:information_desk_person::💁
:O:\`:information_source::ℹ
:O:\`:innocent::😇
:O:\`:interrobang::⁉
:O:\`:iphone::📱
:O:\`:iran::🇮🇷
:O:\`:iraq::🇮🇶
:O:\`:ireland::🇮🇪
:O:\`:isle_of_man::🇮🇲
:O:\`:israel::🇮🇱
:O:\`:it::🇮🇹
:O:\`:izakaya_lantern::🏮
:O:\`:jack_o_lantern::🎃
:O:\`:jamaica::🇯🇲
:O:\`:japan::🗾
:O:\`:japanese_castle::🏯
:O:\`:japanese_goblin::👺
:O:\`:japanese_ogre::👹
:O:\`:jeans::👖
:O:\`:jersey::🇯🇪
:O:\`:jigsaw::🧩
:O:\`:jordan::🇯🇴
:O:\`:joy::😂
:O:\`:joy_cat::😹
:O:\`:joystick::🕹
:O:\`:jp::🇯🇵
:O:\`:judge::🧑⚖
:O:\`:juggling_person::🤹
:O:\`:kaaba::🕋
:O:\`:kangaroo::🦘
:O:\`:kazakhstan::🇰🇿
:O:\`:kenya::🇰🇪
:O:\`:key::🔑
:O:\`:keyboard::⌨
:O:\`:keycap_ten::🔟
:O:\`:kick_scooter::🛴
:O:\`:kimono::👘
:O:\`:kiribati::🇰🇮
:O:\`:kiss::💋
:O:\`:kissing::😗
:O:\`:kissing_cat::😽
:O:\`:kissing_closed_eyes::😚
:O:\`:kissing_heart::😘
:O:\`:kissing_smiling_eyes::😙
:O:\`:kite::🪁
:O:\`:kiwi_fruit::🥝
:O:\`:kneeling_man::🧎♂
:O:\`:kneeling_person::🧎
:O:\`:kneeling_woman::🧎♀
:O:\`:knife::🔪
:O:\`:knot::🪢
:O:\`:koala::🐨
:O:\`:koko::🈁
:O:\`:kosovo::🇽🇰
:O:\`:kr::🇰🇷
:O:\`:kuwait::🇰🇼
:O:\`:kyrgyzstan::🇰🇬
:O:\`:lab_coat::🥼
:O:\`:label::🏷
:O:\`:lacrosse::🥍
:O:\`:ladder::🪜
:O:\`:lady_beetle::🐞
:O:\`:lantern::🏮
:O:\`:laos::🇱🇦
:O:\`:large_blue_circle::🔵
:O:\`:large_blue_diamond::🔷
:O:\`:large_orange_diamond::🔶
:O:\`:last_quarter_moon::🌗
:O:\`:last_quarter_moon_with_face::🌜
:O:\`:latin_cross::✝
:O:\`:latvia::🇱🇻
:O:\`:laughing::😆
:O:\`:leafy_green::🥬
:O:\`:leaves::🍃
:O:\`:lebanon::🇱🇧
:O:\`:ledger::📒
:O:\`:left_luggage::🛅
:O:\`:left_right_arrow::↔
:O:\`:left_speech_bubble::🗨
:O:\`:leftwards_arrow_with_hook::↩
:O:\`:leg::🦵
:O:\`:lemon::🍋
:O:\`:leo::♌
:O:\`:leopard::🐆
:O:\`:lesotho::🇱🇸
:O:\`:level_slider::🎚
:O:\`:liberia::🇱🇷
:O:\`:libra::♎
:O:\`:libya::🇱🇾
:O:\`:liechtenstein::🇱🇮
:O:\`:light_rail::🚈
:O:\`:link::🔗
:O:\`:lion::🦁
:O:\`:lips::👄
:O:\`:lipstick::💄
:O:\`:lithuania::🇱🇹
:O:\`:lizard::🦎
:O:\`:llama::🦙
:O:\`:lobster::🦞
:O:\`:lock::🔒
:O:\`:lock_with_ink_pen::🔏
:O:\`:lollipop::🍭
:O:\`:long_drum::🪘
:O:\`:loop::➿
:O:\`:lotion_bottle::🧴
:O:\`:lotus_position::🧘
:O:\`:lotus_position_man::🧘♂
:O:\`:lotus_position_woman::🧘♀
:O:\`:loud_sound::🔊
:O:\`:loudspeaker::📢
:O:\`:love_hotel::🏩
:O:\`:love_letter::💌
:O:\`:love_you_gesture::🤟
:O:\`:low_brightness::🔅
:O:\`:luggage::🧳
:O:\`:lungs::🫁
:O:\`:luxembourg::🇱🇺
:O:\`:lying_face::🤥
:O:\`:m::Ⓜ
:O:\`:macau::🇲🇴
:O:\`:macedonia::🇲🇰
:O:\`:madagascar::🇲🇬
:O:\`:mag::🔍
:O:\`:mag_right::🔎
:O:\`:mage::🧙
:O:\`:mage_man::🧙♂
:O:\`:mage_woman::🧙♀
:O:\`:magic_wand::🪄
:O:\`:magnet::🧲
:O:\`:mahjong::🀄
:O:\`:mailbox::📫
:O:\`:mailbox_closed::📪
:O:\`:mailbox_with_mail::📬
:O:\`:mailbox_with_no_mail::📭
:O:\`:malawi::🇲🇼
:O:\`:malaysia::🇲🇾
:O:\`:maldives::🇲🇻
:O:\`:male_detective::🕵♂
:O:\`:male_sign::♂
:O:\`:mali::🇲🇱
:O:\`:malta::🇲🇹
:O:\`:mammoth::🦣
:O:\`:man::👨
:O:\`:man_artist::👨🎨
:O:\`:man_astronaut::👨🚀
:O:\`:man_beard::🧔♂
:O:\`:man_cartwheeling::🤸♂
:O:\`:man_cook::👨🍳
:O:\`:man_dancing::🕺
:O:\`:man_facepalming::🤦♂
:O:\`:man_factory_worker::👨🏭
:O:\`:man_farmer::👨🌾
:O:\`:man_feeding_baby::👨🍼
:O:\`:man_firefighter::👨🚒
:O:\`:man_health_worker::👨⚕
:O:\`:man_in_manual_wheelchair::👨🦽
:O:\`:man_in_motorized_wheelchair::👨🦼
:O:\`:man_in_tuxedo::🤵♂
:O:\`:man_judge::👨⚖
:O:\`:man_juggling::🤹♂
:O:\`:man_mechanic::👨🔧
:O:\`:man_office_worker::👨💼
:O:\`:man_pilot::👨✈
:O:\`:man_playing_handball::🤾♂
:O:\`:man_playing_water_polo::🤽♂
:O:\`:man_scientist::👨🔬
:O:\`:man_shrugging::🤷♂
:O:\`:man_singer::👨🎤
:O:\`:man_student::👨🎓
:O:\`:man_teacher::👨🏫
:O:\`:man_technologist::👨💻
:O:\`:man_with_gua_pi_mao::👲
:O:\`:man_with_probing_cane::👨🦯
:O:\`:man_with_turban::👳♂
:O:\`:man_with_veil::👰♂
:O:\`:mandarin::🍊
:O:\`:mango::🥭
:O:\`:mans_shoe::👞
:O:\`:mantelpiece_clock::🕰
:O:\`:manual_wheelchair::🦽
:O:\`:maple_leaf::🍁
:O:\`:marshall_islands::🇲🇭
:O:\`:martial_arts_uniform::🥋
:O:\`:martinique::🇲🇶
:O:\`:mask::😷
:O:\`:massage::💆
:O:\`:massage_man::💆♂
:O:\`:massage_woman::💆♀
:O:\`:mate::🧉
:O:\`:mauritania::🇲🇷
:O:\`:mauritius::🇲🇺
:O:\`:mayotte::🇾🇹
:O:\`:meat_on_bone::🍖
:O:\`:mechanic::🧑🔧
:O:\`:mechanical_arm::🦾
:O:\`:mechanical_leg::🦿
:O:\`:medal_military::🎖
:O:\`:medal_sports::🏅
:O:\`:medical_symbol::⚕
:O:\`:mega::📣
:O:\`:melon::🍈
:O:\`:memo::📝
:O:\`:men_wrestling::🤼♂
:O:\`:mending_heart::❤🩹
:O:\`:menorah::🕎
:O:\`:mens::🚹
:O:\`:mermaid::🧜♀
:O:\`:merman::🧜♂
:O:\`:merperson::🧜
:O:\`:metal::🤘
:O:\`:metro::🚇
:O:\`:mexico::🇲🇽
:O:\`:microbe::🦠
:O:\`:micronesia::🇫🇲
:O:\`:microphone::🎤
:O:\`:microscope::🔬
:O:\`:middle_finger::🖕
:O:\`:military_helmet::🪖
:O:\`:milk_glass::🥛
:O:\`:milky_way::🌌
:O:\`:minibus::🚐
:O:\`:minidisc::💽
:O:\`:mirror::🪞
:O:\`:mobile_phone_off::📴
:O:\`:moldova::🇲🇩
:O:\`:monaco::🇲🇨
:O:\`:money_mouth_face::🤑
:O:\`:money_with_wings::💸
:O:\`:moneybag::💰
:O:\`:mongolia::🇲🇳
:O:\`:monkey::🐒
:O:\`:monkey_face::🐵
:O:\`:monocle_face::🧐
:O:\`:monorail::🚝
:O:\`:montenegro::🇲🇪
:O:\`:montserrat::🇲🇸
:O:\`:moon::🌔
:O:\`:moon_cake::🥮
:O:\`:morocco::🇲🇦
:O:\`:mortar_board::🎓
:O:\`:mosque::🕌
:O:\`:mosquito::🦟
:O:\`:motor_boat::🛥
:O:\`:motor_scooter::🛵
:O:\`:motorcycle::🏍
:O:\`:motorized_wheelchair::🦼
:O:\`:motorway::🛣
:O:\`:mount_fuji::🗻
:O:\`:mountain::⛰
:O:\`:mountain_bicyclist::🚵
:O:\`:mountain_biking_man::🚵♂
:O:\`:mountain_biking_woman::🚵♀
:O:\`:mountain_cableway::🚠
:O:\`:mountain_railway::🚞
:O:\`:mountain_snow::🏔
:O:\`:mouse::🐭
:O:\`:mouse2::🐁
:O:\`:mouse_trap::🪤
:O:\`:movie_camera::🎥
:O:\`:moyai::🗿
:O:\`:mozambique::🇲🇿
:O:\`:mrs_claus::🤶
:O:\`:muscle::💪
:O:\`:mushroom::🍄
:O:\`:musical_keyboard::🎹
:O:\`:musical_note::🎵
:O:\`:musical_score::🎼
:O:\`:mute::🔇
:O:\`:mx_claus::🧑🎄
:O:\`:myanmar::🇲🇲
:O:\`:nail_care::💅
:O:\`:name_badge::📛
:O:\`:namibia::🇳🇦
:O:\`:national_park::🏞
:O:\`:nauru::🇳🇷
:O:\`:nauseated_face::🤢
:O:\`:nazar_amulet::🧿
:O:\`:necktie::👔
:O:\`:negative_squared_cross_mark::❎
:O:\`:nepal::🇳🇵
:O:\`:nerd_face::🤓
:O:\`:nesting_dolls::🪆
:O:\`:netherlands::🇳🇱
:O:\`:neutral_face::😐
:O:\`:new::🆕
:O:\`:new_caledonia::🇳🇨
:O:\`:new_moon::🌑
:O:\`:new_moon_with_face::🌚
:O:\`:new_zealand::🇳🇿
:O:\`:newspaper::📰
:O:\`:newspaper_roll::🗞
:O:\`:next_track_button::⏭
:O:\`:ng::🆖
:O:\`:ng_man::🙅♂
:O:\`:ng_woman::🙅♀
:O:\`:nicaragua::🇳🇮
:O:\`:niger::🇳🇪
:O:\`:nigeria::🇳🇬
:O:\`:night_with_stars::🌃
:O:\`:nine::9⃣
:O:\`:ninja::🥷
:O:\`:niue::🇳🇺
:O:\`:no_bell::🔕
:O:\`:no_bicycles::🚳
:O:\`:no_entry::⛔
:O:\`:no_entry_sign::🚫
:O:\`:no_good::🙅
:O:\`:no_good_man::🙅♂
:O:\`:no_good_woman::🙅♀
:O:\`:no_mobile_phones::📵
:O:\`:no_mouth::😶
:O:\`:no_pedestrians::🚷
:O:\`:no_smoking::🚭
:O:\`:non-potable_water::🚱
:O:\`:norfolk_island::🇳🇫
:O:\`:north_korea::🇰🇵
:O:\`:northern_mariana_islands::🇲🇵
:O:\`:norway::🇳🇴
:O:\`:nose::👃
:O:\`:notebook::📓
:O:\`:notebook_with_decorative_cover::📔
:O:\`:notes::🎶
:O:\`:nut_and_bolt::🔩
:O:\`:o::⭕
:O:\`:o2::🅾
:O:\`:ocean::🌊
:O:\`:octopus::🐙
:O:\`:oden::🍢
:O:\`:office::🏢
:O:\`:office_worker::🧑💼
:O:\`:oil_drum::🛢
:O:\`:ok::🆗
:O:\`:ok_hand::👌
:O:\`:ok_man::🙆♂
:O:\`:ok_person::🙆
:O:\`:ok_woman::🙆♀
:O:\`:old_key::🗝
:O:\`:older_adult::🧓
:O:\`:older_man::👴
:O:\`:older_woman::👵
:O:\`:olive::🫒
:O:\`:om::🕉
:O:\`:oman::🇴🇲
:O:\`:on::🔛
:O:\`:oncoming_automobile::🚘
:O:\`:oncoming_bus::🚍
:O:\`:oncoming_police_car::🚔
:O:\`:oncoming_taxi::🚖
:O:\`:one::1⃣
:O:\`:one_piece_swimsuit::🩱
:O:\`:onion::🧅
:O:\`:open_book::📖
:O:\`:open_file_folder::📂
:O:\`:open_hands::👐
:O:\`:open_mouth::😮
:O:\`:open_umbrella::☂
:O:\`:ophiuchus::⛎
:O:\`:orange::🍊
:O:\`:orange_book::📙
:O:\`:orange_circle::🟠
:O:\`:orange_heart::🧡
:O:\`:orange_square::🟧
:O:\`:orangutan::🦧
:O:\`:orthodox_cross::☦
:O:\`:otter::🦦
:O:\`:outbox_tray::📤
:O:\`:owl::🦉
:O:\`:ox::🐂
:O:\`:oyster::🦪
:O:\`:package::📦
:O:\`:page_facing_up::📄
:O:\`:page_with_curl::📃
:O:\`:pager::📟
:O:\`:paintbrush::🖌
:O:\`:pakistan::🇵🇰
:O:\`:palau::🇵🇼
:O:\`:palestinian_territories::🇵🇸
:O:\`:palm_tree::🌴
:O:\`:palms_up_together::🤲
:O:\`:panama::🇵🇦
:O:\`:pancakes::🥞
:O:\`:panda_face::🐼
:O:\`:paperclip::📎
:O:\`:paperclips::🖇
:O:\`:papua_new_guinea::🇵🇬
:O:\`:parachute::🪂
:O:\`:paraguay::🇵🇾
:O:\`:parasol_on_ground::⛱
:O:\`:parking::🅿
:O:\`:parrot::🦜
:O:\`:part_alternation_mark::〽
:O:\`:partly_sunny::⛅
:O:\`:partying_face::🥳
:O:\`:passenger_ship::🛳
:O:\`:passport_control::🛂
:O:\`:pause_button::⏸
:O:\`:paw_prints::🐾
:O:\`:peace_symbol::☮
:O:\`:peach::🍑
:O:\`:peacock::🦚
:O:\`:peanuts::🥜
:O:\`:pear::🍐
:O:\`:pen::🖊
:O:\`:pencil::📝
:O:\`:pencil2::✏
:O:\`:penguin::🐧
:O:\`:pensive::😔
:O:\`:people_holding_hands::🧑🤝🧑
:O:\`:people_hugging::🫂
:O:\`:performing_arts::🎭
:O:\`:persevere::😣
:O:\`:person_bald::🧑🦲
:O:\`:person_curly_hair::🧑🦱
:O:\`:person_feeding_baby::🧑🍼
:O:\`:person_fencing::🤺
:O:\`:person_in_manual_wheelchair::🧑🦽
:O:\`:person_in_motorized_wheelchair::🧑🦼
:O:\`:person_in_tuxedo::🤵
:O:\`:person_red_hair::🧑🦰
:O:\`:person_white_hair::🧑🦳
:O:\`:person_with_probing_cane::🧑🦯
:O:\`:person_with_turban::👳
:O:\`:person_with_veil::👰
:O:\`:peru::🇵🇪
:O:\`:petri_dish::🧫
:O:\`:philippines::🇵🇭
:O:\`:phone::☎
:O:\`:pick::⛏
:O:\`:pickup_truck::🛻
:O:\`:pie::🥧
:O:\`:pig::🐷
:O:\`:pig2::🐖
:O:\`:pig_nose::🐽
:O:\`:pill::💊
:O:\`:pilot::🧑✈
:O:\`:pinata::🪅
:O:\`:pinched_fingers::🤌
:O:\`:pinching_hand::🤏
:O:\`:pineapple::🍍
:O:\`:ping_pong::🏓
:O:\`:pirate_flag::🏴☠
:O:\`:pisces::♓
:O:\`:pitcairn_islands::🇵🇳
:O:\`:pizza::🍕
:O:\`:placard::🪧
:O:\`:place_of_worship::🛐
:O:\`:plate_with_cutlery::🍽
:O:\`:play_or_pause_button::⏯
:O:\`:pleading_face::🥺
:O:\`:plunger::🪠
:O:\`:point_down::👇
:O:\`:point_left::👈
:O:\`:point_right::👉
:O:\`:point_up::☝
:O:\`:point_up_2::👆
:O:\`:poland::🇵🇱
:O:\`:polar_bear::🐻❄
:O:\`:police_car::🚓
:O:\`:police_officer::👮
:O:\`:policeman::👮♂
:O:\`:policewoman::👮♀
:O:\`:poodle::🐩
:O:\`:poop::💩
:O:\`:popcorn::🍿
:O:\`:portugal::🇵🇹
:O:\`:post_office::🏣
:O:\`:postal_horn::📯
:O:\`:postbox::📮
:O:\`:potable_water::🚰
:O:\`:potato::🥔
:O:\`:potted_plant::🪴
:O:\`:pouch::👝
:O:\`:poultry_leg::🍗
:O:\`:pound::💷
:O:\`:pout::😡
:O:\`:pouting_cat::😾
:O:\`:pouting_face::🙎
:O:\`:pouting_man::🙎♂
:O:\`:pouting_woman::🙎♀
:O:\`:pray::🙏
:O:\`:prayer_beads::📿
:O:\`:pregnant_woman::🤰
:O:\`:pretzel::🥨
:O:\`:previous_track_button::⏮
:O:\`:prince::🤴
:O:\`:princess::👸
:O:\`:printer::🖨
:O:\`:probing_cane::🦯
:O:\`:puerto_rico::🇵🇷
:O:\`:punch::👊
:O:\`:purple_circle::🟣
:O:\`:purple_heart::💜
:O:\`:purple_square::🟪
:O:\`:purse::👛
:O:\`:pushpin::📌
:O:\`:put_litter_in_its_place::🚮
:O:\`:qatar::🇶🇦
:O:\`:question::❓
:O:\`:rabbit::🐰
:O:\`:rabbit2::🐇
:O:\`:raccoon::🦝
:O:\`:racehorse::🐎
:O:\`:racing_car::🏎
:O:\`:radio::📻
:O:\`:radio_button::🔘
:O:\`:radioactive::☢
:O:\`:rage::😡
:O:\`:railway_car::🚃
:O:\`:railway_track::🛤
:O:\`:rainbow::🌈
:O:\`:rainbow_flag::🏳🌈
:O:\`:raised_back_of_hand::🤚
:O:\`:raised_eyebrow::🤨
:O:\`:raised_hand::✋
:O:\`:raised_hand_with_fingers_splayed::🖐
:O:\`:raised_hands::🙌
:O:\`:raising_hand::🙋
:O:\`:raising_hand_man::🙋♂
:O:\`:raising_hand_woman::🙋♀
:O:\`:ram::🐏
:O:\`:ramen::🍜
:O:\`:rat::🐀
:O:\`:razor::🪒
:O:\`:receipt::🧾
:O:\`:record_button::⏺
:O:\`:recycle::♻
:O:\`:red_car::🚗
:O:\`:red_circle::🔴
:O:\`:red_envelope::🧧
:O:\`:red_haired_man::👨🦰
:O:\`:red_haired_woman::👩🦰
:O:\`:red_square::🟥
:O:\`:registered::®
:O:\`:relaxed::☺
:O:\`:relieved::😌
:O:\`:reminder_ribbon::🎗
:O:\`:repeat::🔁
:O:\`:repeat_one::🔂
:O:\`:rescue_worker_helmet::⛑
:O:\`:restroom::🚻
:O:\`:reunion::🇷🇪
:O:\`:revolving_hearts::💞
:O:\`:rewind::⏪
:O:\`:rhinoceros::🦏
:O:\`:ribbon::🎀
:O:\`:rice::🍚
:O:\`:rice_ball::🍙
:O:\`:rice_cracker::🍘
:O:\`:rice_scene::🎑
:O:\`:right_anger_bubble::🗯
:O:\`:ring::💍
:O:\`:ringed_planet::🪐
:O:\`:robot::🤖
:O:\`:rock::🪨
:O:\`:rocket::🚀
:O:\`:rofl::🤣
:O:\`:roll_eyes::🙄
:O:\`:roll_of_paper::🧻
:O:\`:roller_coaster::🎢
:O:\`:roller_skate::🛼
:O:\`:romania::🇷🇴
:O:\`:rooster::🐓
:O:\`:rose::🌹
:O:\`:rosette::🏵
:O:\`:rotating_light::🚨
:O:\`:round_pushpin::📍
:O:\`:rowboat::🚣
:O:\`:rowing_man::🚣♂
:O:\`:rowing_woman::🚣♀
:O:\`:ru::🇷🇺
:O:\`:rugby_football::🏉
:O:\`:runner::🏃
:O:\`:running::🏃
:O:\`:running_man::🏃♂
:O:\`:running_shirt_with_sash::🎽
:O:\`:running_woman::🏃♀
:O:\`:rwanda::🇷🇼
:O:\`:sa::🈂
:O:\`:safety_pin::🧷
:O:\`:safety_vest::🦺
:O:\`:sagittarius::♐
:O:\`:sailboat::⛵
:O:\`:sake::🍶
:O:\`:salt::🧂
:O:\`:samoa::🇼🇸
:O:\`:san_marino::🇸🇲
:O:\`:sandal::👡
:O:\`:sandwich::🥪
:O:\`:santa::🎅
:O:\`:sao_tome_principe::🇸🇹
:O:\`:sari::🥻
:O:\`:sassy_man::💁♂
:O:\`:sassy_woman::💁♀
:O:\`:satellite::📡
:O:\`:satisfied::😆
:O:\`:saudi_arabia::🇸🇦
:O:\`:sauna_man::🧖♂
:O:\`:sauna_person::🧖
:O:\`:sauna_woman::🧖♀
:O:\`:sauropod::🦕
:O:\`:saxophone::🎷
:O:\`:scarf::🧣
:O:\`:school::🏫
:O:\`:school_satchel::🎒
:O:\`:scientist::🧑🔬
:O:\`:scissors::✂
:O:\`:scorpion::🦂
:O:\`:scorpius::♏
:O:\`:scotland::🏴󠁧󠁢󠁳󠁣󠁴󠁿
:O:\`:scream::😱
:O:\`:scream_cat::🙀
:O:\`:screwdriver::🪛
:O:\`:scroll::📜
:O:\`:seal::🦭
:O:\`:seat::💺
:O:\`:secret::㊙
:O:\`:see_no_evil::🙈
:O:\`:seedling::🌱
:O:\`:selfie::🤳
:O:\`:senegal::🇸🇳
:O:\`:serbia::🇷🇸
:O:\`:service_dog::🐕🦺
:O:\`:seven::7⃣
:O:\`:sewing_needle::🪡
:O:\`:seychelles::🇸🇨
:O:\`:shallow_pan_of_food::🥘
:O:\`:shamrock::☘
:O:\`:shark::🦈
:O:\`:shaved_ice::🍧
:O:\`:sheep::🐑
:O:\`:shell::🐚
:O:\`:shield::🛡
:O:\`:shinto_shrine::⛩
:O:\`:ship::🚢
:O:\`:shirt::👕
:O:\`:shit::💩
:O:\`:shoe::👞
:O:\`:shopping::🛍
:O:\`:shopping_cart::🛒
:O:\`:shorts::🩳
:O:\`:shower::🚿
:O:\`:shrimp::🦐
:O:\`:shrug::🤷
:O:\`:shushing_face::🤫
:O:\`:sierra_leone::🇸🇱
:O:\`:signal_strength::📶
:O:\`:singapore::🇸🇬
:O:\`:singer::🧑🎤
:O:\`:sint_maarten::🇸🇽
:O:\`:six::6⃣
:O:\`:six_pointed_star::🔯
:O:\`:skateboard::🛹
:O:\`:ski::🎿
:O:\`:skier::⛷
:O:\`:skull::💀
:O:\`:skull_and_crossbones::☠
:O:\`:skunk::🦨
:O:\`:sled::🛷
:O:\`:sleeping::😴
:O:\`:sleeping_bed::🛌
:O:\`:sleepy::😪
:O:\`:slightly_frowning_face::🙁
:O:\`:slightly_smiling_face::🙂
:O:\`:slot_machine::🎰
:O:\`:sloth::🦥
:O:\`:slovakia::🇸🇰
:O:\`:slovenia::🇸🇮
:O:\`:small_airplane::🛩
:O:\`:small_blue_diamond::🔹
:O:\`:small_orange_diamond::🔸
:O:\`:small_red_triangle::🔺
:O:\`:small_red_triangle_down::🔻
:O:\`:smile::😄
:O:\`:smile_cat::😸
:O:\`:smiley::😃
:O:\`:smiley_cat::😺
:O:\`:smiling_face_with_tear::🥲
:O:\`:smiling_face_with_three_hearts::🥰
:O:\`:smiling_imp::😈
:O:\`:smirk::😏
:O:\`:smirk_cat::😼
:O:\`:smoking::🚬
:O:\`:snail::🐌
:O:\`:snake::🐍
:O:\`:sneezing_face::🤧
:O:\`:snowboarder::🏂
:O:\`:snowflake::❄
:O:\`:snowman::⛄
:O:\`:snowman_with_snow::☃
:O:\`:soap::🧼
:O:\`:sob::😭
:O:\`:soccer::⚽
:O:\`:socks::🧦
:O:\`:softball::🥎
:O:\`:solomon_islands::🇸🇧
:O:\`:somalia::🇸🇴
:O:\`:soon::🔜
:O:\`:sos::🆘
:O:\`:sound::🔉
:O:\`:south_africa::🇿🇦
:O:\`:south_georgia_south_sandwich_islands::🇬🇸
:O:\`:south_sudan::🇸🇸
:O:\`:space_invader::👾
:O:\`:spades::♠
:O:\`:spaghetti::🍝
:O:\`:sparkle::❇
:O:\`:sparkler::🎇
:O:\`:sparkles::✨
:O:\`:sparkling_heart::💖
:O:\`:speak_no_evil::🙊
:O:\`:speaker::🔈
:O:\`:speaking_head::🗣
:O:\`:speech_balloon::💬
:O:\`:speedboat::🚤
:O:\`:spider::🕷
:O:\`:spider_web::🕸
:O:\`:spiral_calendar::🗓
:O:\`:spiral_notepad::🗒
:O:\`:sponge::🧽
:O:\`:spoon::🥄
:O:\`:squid::🦑
:O:\`:sri_lanka::🇱🇰
:O:\`:st_barthelemy::🇧🇱
:O:\`:st_helena::🇸🇭
:O:\`:st_kitts_nevis::🇰🇳
:O:\`:st_lucia::🇱🇨
:O:\`:st_martin::🇲🇫
:O:\`:st_pierre_miquelon::🇵🇲
:O:\`:st_vincent_grenadines::🇻🇨
:O:\`:stadium::🏟
:O:\`:standing_man::🧍♂
:O:\`:standing_person::🧍
:O:\`:standing_woman::🧍♀
:O:\`:star::⭐
:O:\`:star2::🌟
:O:\`:star_and_crescent::☪
:O:\`:star_of_david::✡
:O:\`:star_struck::🤩
:O:\`:stars::🌠
:O:\`:station::🚉
:O:\`:statue_of_liberty::🗽
:O:\`:steam_locomotive::🚂
:O:\`:stethoscope::🩺
:O:\`:stew::🍲
:O:\`:stop_button::⏹
:O:\`:stop_sign::🛑
:O:\`:stopwatch::⏱
:O:\`:straight_ruler::📏
:O:\`:strawberry::🍓
:O:\`:stuck_out_tongue::😛
:O:\`:stuck_out_tongue_closed_eyes::😝
:O:\`:stuck_out_tongue_winking_eye::😜
:O:\`:student::🧑🎓
:O:\`:studio_microphone::🎙
:O:\`:stuffed_flatbread::🥙
:O:\`:sudan::🇸🇩
:O:\`:sun_behind_large_cloud::🌥
:O:\`:sun_behind_rain_cloud::🌦
:O:\`:sun_behind_small_cloud::🌤
:O:\`:sun_with_face::🌞
:O:\`:sunflower::🌻
:O:\`:sunglasses::😎
:O:\`:sunny::☀
:O:\`:sunrise::🌅
:O:\`:sunrise_over_mountains::🌄
:O:\`:superhero::🦸
:O:\`:superhero_man::🦸♂
:O:\`:superhero_woman::🦸♀
:O:\`:supervillain::🦹
:O:\`:supervillain_man::🦹♂
:O:\`:supervillain_woman::🦹♀
:O:\`:surfer::🏄
:O:\`:surfing_man::🏄♂
:O:\`:surfing_woman::🏄♀
:O:\`:suriname::🇸🇷
:O:\`:sushi::🍣
:O:\`:suspension_railway::🚟
:O:\`:svalbard_jan_mayen::🇸🇯
:O:\`:swan::🦢
:O:\`:swaziland::🇸🇿
:O:\`:sweat::😓
:O:\`:sweat_drops::💦
:O:\`:sweat_smile::😅
:O:\`:sweden::🇸🇪
:O:\`:sweet_potato::🍠
:O:\`:swim_brief::🩲
:O:\`:swimmer::🏊
:O:\`:swimming_man::🏊♂
:O:\`:swimming_woman::🏊♀
:O:\`:switzerland::🇨🇭
:O:\`:symbols::🔣
:O:\`:synagogue::🕍
:O:\`:syria::🇸🇾
:O:\`:syringe::💉
:O:\`:t-rex::🦖
:O:\`:taco::🌮
:O:\`:tada::🎉
:O:\`:taiwan::🇹🇼
:O:\`:tajikistan::🇹🇯
:O:\`:takeout_box::🥡
:O:\`:tamale::🫔
:O:\`:tanabata_tree::🎋
:O:\`:tangerine::🍊
:O:\`:tanzania::🇹🇿
:O:\`:taurus::♉
:O:\`:taxi::🚕
:O:\`:tea::🍵
:O:\`:teacher::🧑🏫
:O:\`:teapot::🫖
:O:\`:technologist::🧑💻
:O:\`:teddy_bear::🧸
:O:\`:telephone::☎
:O:\`:telephone_receiver::📞
:O:\`:telescope::🔭
:O:\`:tennis::🎾
:O:\`:tent::⛺
:O:\`:test_tube::🧪
:O:\`:thailand::🇹🇭
:O:\`:thermometer::🌡
:O:\`:thinking::🤔
:O:\`:thong_sandal::🩴
:O:\`:thought_balloon::💭
:O:\`:thread::🧵
:O:\`:three::3⃣
:O:\`:thumbsdown::👎
:O:\`:thumbsup::👍
:O:\`:ticket::🎫
:O:\`:tickets::🎟
:O:\`:tiger::🐯
:O:\`:tiger2::🐅
:O:\`:timer_clock::⏲
:O:\`:timor_leste::🇹🇱
:O:\`:tipping_hand_man::💁♂
:O:\`:tipping_hand_person::💁
:O:\`:tipping_hand_woman::💁♀
:O:\`:tired_face::😫
:O:\`:tm::™
:O:\`:togo::🇹🇬
:O:\`:toilet::🚽
:O:\`:tokelau::🇹🇰
:O:\`:tokyo_tower::🗼
:O:\`:tomato::🍅
:O:\`:tonga::🇹🇴
:O:\`:tongue::👅
:O:\`:toolbox::🧰
:O:\`:tooth::🦷
:O:\`:toothbrush::🪥
:O:\`:top::🔝
:O:\`:tophat::🎩
:O:\`:tornado::🌪
:O:\`:tr::🇹🇷
:O:\`:trackball::🖲
:O:\`:tractor::🚜
:O:\`:traffic_light::🚥
:O:\`:train::🚋
:O:\`:train2::🚆
:O:\`:tram::🚊
:O:\`:transgender_flag::🏳⚧
:O:\`:transgender_symbol::⚧
:O:\`:triangular_flag_on_post::🚩
:O:\`:triangular_ruler::📐
:O:\`:trident::🔱
:O:\`:trinidad_tobago::🇹🇹
:O:\`:tristan_da_cunha::🇹🇦
:O:\`:triumph::😤
:O:\`:trolleybus::🚎
:O:\`:trophy::🏆
:O:\`:tropical_drink::🍹
:O:\`:tropical_fish::🐠
:O:\`:truck::🚚
:O:\`:trumpet::🎺
:O:\`:tshirt::👕
:O:\`:tulip::🌷
:O:\`:tumbler_glass::🥃
:O:\`:tunisia::🇹🇳
:O:\`:turkey::🦃
:O:\`:turkmenistan::🇹🇲
:O:\`:turks_caicos_islands::🇹🇨
:O:\`:turtle::🐢
:O:\`:tuvalu::🇹🇻
:O:\`:tv::📺
:O:\`:twisted_rightwards_arrows::🔀
:O:\`:two::2⃣
:O:\`:two_hearts::💕
:O:\`:two_men_holding_hands::👬
:O:\`:two_women_holding_hands::👭
:O:\`:u5272::🈹
:O:\`:u5408::🈴
:O:\`:u55b6::🈺
:O:\`:u6307::🈯
:O:\`:u6708::🈷
:O:\`:u6709::🈶
:O:\`:u6e80::🈵
:O:\`:u7121::🈚
:O:\`:u7533::🈸
:O:\`:u7981::🈲
:O:\`:u7a7a::🈳
:O:\`:uganda::🇺🇬
:O:\`:uk::🇬🇧
:O:\`:ukraine::🇺🇦
:O:\`:umbrella::☔
:O:\`:unamused::😒
:O:\`:underage::🔞
:O:\`:unicorn::🦄
:O:\`:united_arab_emirates::🇦🇪
:O:\`:united_nations::🇺🇳
:O:\`:unlock::🔓
:O:\`:up::🆙
:O:\`:upside_down_face::🙃
:O:\`:uruguay::🇺🇾
:O:\`:us::🇺🇸
:O:\`:us_outlying_islands::🇺🇲
:O:\`:us_virgin_islands::🇻🇮
:O:\`:uzbekistan::🇺🇿
:O:\`:v::✌
:O:\`:vampire::🧛
:O:\`:vampire_man::🧛♂
:O:\`:vampire_woman::🧛♀
:O:\`:vanuatu::🇻🇺
:O:\`:vatican_city::🇻🇦
:O:\`:venezuela::🇻🇪
:O:\`:vertical_traffic_light::🚦
:O:\`:vhs::📼
:O:\`:vibration_mode::📳
:O:\`:video_camera::📹
:O:\`:video_game::🎮
:O:\`:vietnam::🇻🇳
:O:\`:violin::🎻
:O:\`:virgo::♍
:O:\`:volcano::🌋
:O:\`:volleyball::🏐
:O:\`:vomiting_face::🤮
:O:\`:vs::🆚
:O:\`:vulcan_salute::🖖
:O:\`:waffle::🧇
:O:\`:wales::🏴󠁧󠁢󠁷󠁬󠁳󠁿
:O:\`:walking::🚶
:O:\`:walking_man::🚶♂
:O:\`:walking_woman::🚶♀
:O:\`:wallis_futuna::🇼🇫
:O:\`:waning_crescent_moon::🌘
:O:\`:waning_gibbous_moon::🌖
:O:\`:warning::⚠
:O:\`:wastebasket::🗑
:O:\`:watch::⌚
:O:\`:water_buffalo::🐃
:O:\`:water_polo::🤽
:O:\`:watermelon::🍉
:O:\`:wave::👋
:O:\`:wavy_dash::〰
:O:\`:waxing_crescent_moon::🌒
:O:\`:waxing_gibbous_moon::🌔
:O:\`:wc::🚾
:O:\`:weary::😩
:O:\`:wedding::💒
:O:\`:weight_lifting::🏋
:O:\`:weight_lifting_man::🏋♂
:O:\`:weight_lifting_woman::🏋♀
:O:\`:western_sahara::🇪🇭
:O:\`:whale::🐳
:O:\`:whale2::🐋
:O:\`:wheel_of_dharma::☸
:O:\`:wheelchair::♿
:O:\`:white_check_mark::✅
:O:\`:white_circle::⚪
:O:\`:white_flag::🏳
:O:\`:white_flower::💮
:O:\`:white_haired_man::👨🦳
:O:\`:white_haired_woman::👩🦳
:O:\`:white_heart::🤍
:O:\`:white_large_square::⬜
:O:\`:white_medium_small_square::◽
:O:\`:white_medium_square::◻
:O:\`:white_small_square::▫
:O:\`:white_square_button::🔳
:O:\`:wilted_flower::🥀
:O:\`:wind_chime::🎐
:O:\`:wind_face::🌬
:O:\`:window::🪟
:O:\`:wine_glass::🍷
:O:\`:wink::😉
:O:\`:wolf::🐺
:O:\`:woman::👩
:O:\`:woman_artist::👩🎨
:O:\`:woman_astronaut::👩🚀
:O:\`:woman_beard::🧔♀
:O:\`:woman_cartwheeling::🤸♀
:O:\`:woman_cook::👩🍳
:O:\`:woman_dancing::💃
:O:\`:woman_facepalming::🤦♀
:O:\`:woman_factory_worker::👩🏭
:O:\`:woman_farmer::👩🌾
:O:\`:woman_feeding_baby::👩🍼
:O:\`:woman_firefighter::👩🚒
:O:\`:woman_health_worker::👩⚕
:O:\`:woman_in_manual_wheelchair::👩🦽
:O:\`:woman_in_motorized_wheelchair::👩🦼
:O:\`:woman_in_tuxedo::🤵♀
:O:\`:woman_judge::👩⚖
:O:\`:woman_juggling::🤹♀
:O:\`:woman_mechanic::👩🔧
:O:\`:woman_office_worker::👩💼
:O:\`:woman_pilot::👩✈
:O:\`:woman_playing_handball::🤾♀
:O:\`:woman_playing_water_polo::🤽♀
:O:\`:woman_scientist::👩🔬
:O:\`:woman_shrugging::🤷♀
:O:\`:woman_singer::👩🎤
:O:\`:woman_student::👩🎓
:O:\`:woman_teacher::👩🏫
:O:\`:woman_technologist::👩💻
:O:\`:woman_with_headscarf::🧕
:O:\`:woman_with_probing_cane::👩🦯
:O:\`:woman_with_turban::👳♀
:O:\`:woman_with_veil::👰♀
:O:\`:womans_clothes::👚
:O:\`:womans_hat::👒
:O:\`:women_wrestling::🤼♀
:O:\`:womens::🚺
:O:\`:wood::🪵
:O:\`:woozy_face::🥴
:O:\`:world_map::🗺
:O:\`:worm::🪱
:O:\`:worried::😟
:O:\`:wrench::🔧
:O:\`:wrestling::🤼
:O:\`:writing_hand::✍
:O:\`:x::❌
:O:\`:yarn::🧶
:O:\`:yawning_face::🥱
:O:\`:yellow_circle::🟡
:O:\`:yellow_heart::💛
:O:\`:yellow_square::🟨
:O:\`:yemen::🇾🇪
:O:\`:yen::💴
:O:\`:yin_yang::☯
:O:\`:yo_yo::🪀
:O:\`:yum::😋
:O:\`:zambia::🇿🇲
:O:\`:zany_face::🤪
:O:\`:zap::⚡
:O:\`:zebra::🦓
:O:\`:zero::0⃣
:O:\`:zimbabwe::🇿🇼
:O:\`:zipper_mouth_face::🤐
:O:\`:zombie::🧟
:O:\`:zombie_man::🧟♂
:O:\`:zombie_woman::🧟♀
:O:\`:zzz::💤
